/**
 * The Gateway LaunchAgent, installed the supported way: OpenClaw's own
 * `openclaw gateway install --wrapper <path>` writes the plist, its protected
 * service environment and its log locations, and leaves an installation that
 * already matches alone. The repo contributes only the wrapper, which loads
 * the project .env, points OpenClaw at the project config and state, and runs
 * the same OpenClaw CLI that normal Gateway operations resolve.
 *
 * Everything here is pure so the plan can be printed and tested without
 * touching launchd.
 */
import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";

export const GATEWAY_LAUNCHD_LABEL = "ai.openclaw.gateway";
export const GATEWAY_PORT = "18789";
/** Where the running service already expects the wrapper (its persisted OPENCLAW_WRAPPER), relative to HOME. */
export const GATEWAY_WRAPPER_PATH = ".openclaw/bin/ai-assistant-launchd-wrapper";
const SYSTEM_PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";

export function shellQuote(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

/**
 * No Node version directory is written here: the service environment OpenClaw
 * generates already puts its own Node first on PATH, and the wrapper only adds
 * the selected CLI's directory in front of it.
 */
export function buildGatewayWrapperScript({ projectRoot, openclawCommand }) {
  return [
    "#!/bin/sh",
    "# Generated by the assistant repo (npm run install:launchd). Do not edit by hand.",
    "# OpenClaw's LaunchAgent starts the Gateway through this wrapper: it loads the",
    "# project .env, points OpenClaw at the project config and state, and runs the",
    "# OpenClaw CLI that normal Gateway operations use.",
    "set -eu",
    "",
    `project_dir=${shellQuote(projectRoot)}`,
    'if [ -f "$project_dir/.env" ]; then',
    "  set -a",
    '  . "$project_dir/.env"',
    "  set +a",
    "fi",
    "",
    "absolute_project_path() {",
    '  case "$1" in',
    '    /*) printf "%s\\n" "$1" ;;',
    '    *) printf "%s/%s\\n" "$project_dir" "$1" ;;',
    "  esac",
    "}",
    "",
    'export OPENCLAW_CONFIG_PATH="$(absolute_project_path "${OPENCLAW_CONFIG_PATH:-.openclaw/openclaw.json}")"',
    'export OPENCLAW_STATE_DIR="$(absolute_project_path "${OPENCLAW_STATE_DIR:-.openclaw/state}")"',
    `export PATH=${shellQuote(dirname(openclawCommand))}":\${PATH:-}:${SYSTEM_PATH}"`,
    "",
    'cd "$project_dir"',
    `exec ${shellQuote(openclawCommand)} "$@"`,
    "",
  ].join("\n");
}

/** The project directory an installed wrapper starts the Gateway from, or null when it cannot tell. */
export function wrapperProjectDir(content) {
  const match = /^project_dir=(?:'((?:[^']|'\\'')*)'|"([^"$`\\]*)")\s*$/m.exec(String(content ?? ""));
  if (!match) return null;
  return match[1] !== undefined ? match[1].replaceAll("'\\''", "'") : match[2];
}

/**
 * Keeps an existing Gateway token or creates one, mirrored to gateway.remote
 * as before. The token itself never appears in the returned description.
 */
export function ensureGatewayToken(config, { generateToken = () => randomBytes(36).toString("base64url") } = {}) {
  const gateway = config?.gateway ?? {};
  const auth = gateway.auth ?? {};
  const existing = typeof auth.token === "string" && auth.token.length > 0 ? auth.token : null;
  const token = existing ?? generateToken();
  const next = {
    ...config,
    gateway: {
      ...gateway,
      auth: { ...auth, mode: "token", token },
      remote: { ...(gateway.remote ?? {}), token },
    },
  };
  const changed = JSON.stringify(next) !== JSON.stringify(config);
  return { config: next, changed, token: existing ? "kept" : "generated" };
}

/**
 * The environment for `openclaw gateway install`. Values the wrapper loads
 * from the project .env at run time are left out, because OpenClaw copies
 * environment values that config secret references point at (such as the
 * Telegram bot token) into its service environment.
 */
export function buildInstallEnvironment({ processEnv = {}, dotEnvKeys = [], configPath, stateDir }) {
  const skip = new Set(dotEnvKeys);
  const env = Object.fromEntries(Object.entries(processEnv).filter(([key]) => !skip.has(key)));
  return { ...env, OPENCLAW_CONFIG_PATH: configPath, OPENCLAW_STATE_DIR: stateDir };
}

export function planGatewayLaunchdInstall({
  projectRoot,
  home,
  runtime,
  existingWrapper = null,
  config = {},
  port = GATEWAY_PORT,
  force = false,
}) {
  const wrapperPath = join(home, GATEWAY_WRAPPER_PATH);
  const content = buildGatewayWrapperScript({ projectRoot, openclawCommand: runtime.command });
  const wrapperAction = existingWrapper === null ? "create" : existingWrapper === content ? "unchanged" : "update";
  const hasToken = typeof config?.gateway?.auth?.token === "string" && config.gateway.auth.token.length > 0;
  // Installing from another checkout, such as a git worktree, would move the live Gateway there.
  const installedProjectDir = existingWrapper === null ? null : wrapperProjectDir(existingWrapper);
  const projectChange = installedProjectDir && installedProjectDir !== projectRoot ? { from: installedProjectDir, to: projectRoot } : null;

  return {
    label: GATEWAY_LAUNCHD_LABEL,
    projectChange,
    plistPath: join(home, "Library/LaunchAgents", `${GATEWAY_LAUNCHD_LABEL}.plist`),
    runtime: { command: runtime.command, source: runtime.source, version: runtime.version },
    wrapper: { path: wrapperPath, action: wrapperAction, mode: "0700", runs: runtime.command, workingDirectory: projectRoot, content },
    gatewayToken: hasToken ? "keep existing (not shown)" : "generate new (not shown)",
    install: {
      command: runtime.command,
      args: ["gateway", "install", `--wrapper=${wrapperPath}`, `--port=${port}`, ...(force ? ["--force"] : []), "--json"],
    },
    // A service that is already installed keeps running the old wrapper until it restarts.
    restartIfAlreadyInstalled: wrapperAction !== "unchanged",
    logs: {
      stdout: join(home, "Library/Logs/openclaw/gateway.log"),
      note: "OpenClaw's LaunchAgent default; assistant:status reads the path from the installed plist.",
    },
  };
}

export function formatGatewayLaunchdPlan(plan, { dryRun = true } = {}) {
  const runtimeLabel = { explicit: "OPENCLAW_CLI", managed: "managed install", path: "openclaw on PATH" }[plan.runtime.source] ?? plan.runtime.source;
  const wrapperAction = { create: "would be created", update: "would be updated", unchanged: "is already current" }[plan.wrapper.action];
  return [
    dryRun ? "Dry run: nothing was written and launchd was not touched." : "Install plan:",
    ...(plan.projectChange
      ? [`Warning: the installed Gateway runs from ${plan.projectChange.from}; installing from here would move it to ${plan.projectChange.to}. A real install refuses this without --force.`]
      : []),
    `OpenClaw runtime: ${plan.runtime.command} (${runtimeLabel}, OpenClaw ${plan.runtime.version})`,
    `Wrapper: ${plan.wrapper.path} ${wrapperAction}; it runs ${plan.wrapper.runs} from ${plan.wrapper.workingDirectory}.`,
    `Gateway token: ${plan.gatewayToken}.`,
    `Install command: ${[plan.install.command, ...plan.install.args].join(" ")}`,
    `  OpenClaw writes ${plan.plistPath} and its service environment, and leaves a matching installation alone.`,
    `Restart: ${plan.restartIfAlreadyInstalled ? "yes, if OpenClaw reports the service is already installed, so it picks up the new wrapper" : "not needed for the wrapper"}.`,
    `Logs: ${plan.logs.stdout} (${plan.logs.note})`,
  ].join("\n");
}
