#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const projectRoot = resolve(dirname(currentFile), "..");
const home = homedir();
const label = "ai.openclaw.gateway";
const port = "18789";
const launchAgentsDir = resolve(home, "Library/LaunchAgents");
const serviceEnvDir = resolve(home, ".openclaw/service-env");
const plistPath = resolve(launchAgentsDir, `${label}.plist`);
const wrapperPath = resolve(serviceEnvDir, "ai-assistant-launchd-wrapper.sh");
const envPath = resolve(serviceEnvDir, "ai-assistant-launchd.env");
const logDir = resolve(projectRoot, ".openclaw/state/logs");
const stdoutPath = resolve(logDir, "gateway.log");
const stderrPath = resolve(logDir, "gateway.err.log");
const configPath = resolve(projectRoot, ".openclaw/openclaw.json");
const defaultNodeBin = resolve(home, ".nvm/versions/node/v22.22.2/bin/node");
const defaultOpenClawEntry = resolve(home, ".nvm/versions/node/v22.22.2/lib/node_modules/openclaw/dist/index.js");
const nodeBin = process.env.OPENCLAW_NODE_BIN || (existsSync(defaultNodeBin) ? defaultNodeBin : process.execPath);
const openClawEntry = process.env.OPENCLAW_CLI_ENTRY || defaultOpenClawEntry;

function xmlEscape(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    ...options,
  });
  if (result.status !== 0 && !options.allowFailure) {
    const details = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
    throw new Error(`${command} ${args.join(" ")} failed${details ? `:\n${details}` : ""}`);
  }
  return result;
}

if (!existsSync(openClawEntry)) {
  throw new Error(`OpenClaw entrypoint not found: ${openClawEntry}`);
}

if (!existsSync(configPath)) {
  throw new Error(`Rendered OpenClaw config not found: ${configPath}. Run npm run render:config first.`);
}

mkdirSync(launchAgentsDir, { recursive: true });
mkdirSync(serviceEnvDir, { recursive: true });
mkdirSync(logDir, { recursive: true });

const config = JSON.parse(readFileSync(configPath, "utf8"));
const gateway = config.gateway ?? {};
const auth = gateway.auth ?? {};
const token = typeof auth.token === "string" && auth.token.length > 0
  ? auth.token
  : randomBytes(36).toString("base64url");
config.gateway = {
  ...gateway,
  auth: {
    ...auth,
    mode: "token",
    token,
  },
  remote: {
    ...(gateway.remote ?? {}),
    token,
  },
};
writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`);

writeFileSync(
  envPath,
  [
    "# Generated by assistant install-launchd. Do not commit secrets here.",
    `export HOME='${home}'`,
    "export NODE_EXTRA_CA_CERTS='/etc/ssl/cert.pem'",
    "export NODE_USE_SYSTEM_CA='1'",
    `export OPENCLAW_GATEWAY_PORT='${port}'`,
    `export OPENCLAW_LAUNCHD_LABEL='${label}'`,
    "export OPENCLAW_SERVICE_KIND='gateway'",
    "export OPENCLAW_SERVICE_MARKER='openclaw'",
    "export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'",
    `export TMPDIR='${resolve(home, ".openclaw/tmp")}'`,
    "",
  ].join("\n"),
  { mode: 0o600 },
);

writeFileSync(
  wrapperPath,
  `#!/bin/sh
set -eu

env_file="\${1:-}"
if [ -n "$env_file" ] && [ -f "$env_file" ]; then
  shift
  . "$env_file"
fi

project_dir="${projectRoot}"
if [ -f "$project_dir/.env" ]; then
  set -a
  . "$project_dir/.env"
  set +a
fi

absolute_project_path() {
  case "$1" in
    /*) printf "%s\\n" "$1" ;;
    *) printf "%s/%s\\n" "$project_dir" "$1" ;;
  esac
}

export OPENCLAW_CONFIG_PATH="$(absolute_project_path "\${OPENCLAW_CONFIG_PATH:-.openclaw/openclaw.json}")"
export OPENCLAW_STATE_DIR="$(absolute_project_path "\${OPENCLAW_STATE_DIR:-.openclaw/state}")"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

cd "$project_dir"
exec "$@"
`,
  { mode: 0o755 },
);

const args = [
  wrapperPath,
  envPath,
  nodeBin,
  openClawEntry,
  "gateway",
  "--port",
  port,
];

const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${xmlEscape(label)}</string>
  <key>ProgramArguments</key>
  <array>
${args.map((arg) => `    <string>${xmlEscape(arg)}</string>`).join("\n")}
  </array>
  <key>WorkingDirectory</key>
  <string>${xmlEscape(projectRoot)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StandardOutPath</key>
  <string>${xmlEscape(stdoutPath)}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(stderrPath)}</string>
  <key>ExitTimeOut</key>
  <integer>20</integer>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>Umask</key>
  <integer>63</integer>
</dict>
</plist>
`;
writeFileSync(plistPath, plist, { mode: 0o600 });

const domain = `gui/${process.getuid()}`;
run("launchctl", ["bootout", `${domain}/${label}`], { allowFailure: true });
run("launchctl", ["bootout", domain, plistPath], { allowFailure: true });
run("launchctl", ["bootstrap", domain, plistPath]);
run("launchctl", ["kickstart", "-k", `${domain}/${label}`]);

console.log(`Installed LaunchAgent: ${plistPath}`);
console.log(`Wrapper: ${wrapperPath}`);
console.log(`Logs: ${stdoutPath}`);
console.log(`Errors: ${stderrPath}`);
